# Generated by Django 4.1.7 on 2023-02-20 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Название')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=100, verbose_name='Имя')),
                ('password', models.CharField(max_length=20, verbose_name='Пароль')),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=128, verbose_name='Адрес')),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Товар')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='Цена')),
                ('quantity', models.IntegerField(blank=True, null=True, verbose_name='Количество')),
                ('release_date', models.DateField(verbose_name='Дата производства')),
                ('data_upload', models.DateField(auto_now_add=True, db_index=True, verbose_name='Опубликовано')),
                ('data_upgrade', models.DateField(auto_now_add=True, verbose_name='Дата обновления')),
                ('images', models.ImageField(default='img/None/no-img.jpg', upload_to='img/')),
                ('categories', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='viewapp.categories', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.IntegerField(verbose_name='Общая цена')),
                ('order_date', models.DateField(auto_now_add=True)),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viewapp.users')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Количество')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='Цена')),
                ('orders', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viewapp.orders')),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viewapp.products')),
            ],
        ),
    ]
