# Generated by Django 4.1.7 on 2023-02-26 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={},
        ),
        migrations.AlterField(
            model_name='categories',
            name='title',
            field=models.CharField(max_length=30, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='products',
            name='images',
            field=models.ImageField(default='img/None/no-img.jpg', upload_to='img/', verbose_name='Фото'),
        ),
    ]
